name: medit
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - scvi
  - anndata
  - scanpy>=1.9
  - h5py
  - pyarrow
  - numba
  - umap-learn
  - leidenalg
  - statsmodels
  - matplotlib
  - seaborn
  - scikit-misc
  - phate
  - pip:
      - mypy
      - types-requests
      - rich
      - tqdm
